### ISSUE TITLE
ipykernel is not getting initialized

### ISSUE THREAD

**Issue by tariqph** [jplane/pyspark-devcontainer#1]
the ipykernel is not geeting initialized after opening the notebook and I am unable to install pip or ipykernel as it is adsking for  password for jovyan.

**Comment by jplane** [comment]
I updated the devcontainer configuration to include the Jupyter extension, works for me with a clean pull + init.

**Comment by tariqph** [comment]
It's working, thanks so much. I still had to pip install pyspark but it is working.
